/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lyf_app2_MyNDK */

#ifndef _Included_lyf_app2_MyNDK
#define _Included_lyf_app2_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lyf_app2_MyNDK
 * Method:    Add
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lyf_app2_MyNDK_Add
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
