/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lyf_ndkstudy2_MyNDK */

#ifndef _Included_lyf_ndkstudy2_MyNDK
#define _Included_lyf_ndkstudy2_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lyf_ndkstudy2_MyNDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_lyf_ndkstudy2_MyNDK_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
